### ISSUE TITLE
Error messages in kmeans_metab_clust_survival.R

### ISSUE THREAD

**Issue by aElia13** [dBenedek/MetabolicExpressR#1]
In file kmeans_metab_clust_surival.R:

line 31 - `if(!is.numeric(clinical_data[[surv_status_col]])) stop("surv_status_col must be of character type")`
line 32 -  `if(!is.numeric(clinical_data[[surv_time_col]])) stop("surv_time_col must be of character type")`

When variable types are being checked, it checks that the type is numeric, but the warning message tells that it needs to be of type character.

**Comment by dBenedek** [comment]
Thanks, corrected.
